AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'marchante_backend

  Sample SAM Template for marchante_backend

  '
Globals:
  Function:
    Timeout: 5
Resources:
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/a90f9c52f960b442fee7ea4d2279426c
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /register
            Method: POST
      Environment:
        Variables:
          HOST_MAIL: smtp.hostinger.mx
          USER_MAIL: contacto@mimarchante.mx
          PASS_MAIL: '!dSc3i!0mY9'
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
  RegisterUserCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/a90f9c52f960b442fee7ea4d2279426c
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /register
            Method: OPTIONS
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/e3580bbad771cd7c5c407138cdc085ff
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /login
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  LoginCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/e3580bbad771cd7c5c407138cdc085ff
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /login
            Method: OPTIONS
  AddProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/979a8fce206c9cd96134a9347cd29f0f
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /add-products
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  AddProductsCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/5582e1ef645fbdbbe025afdbdef98b3d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-products/{id_user}
            Method: OPTIONS
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/5582e1ef645fbdbbe025afdbdef98b3d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-products/{id_user}
            Method: GET
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/3b38556ae4653ec70f876f2417e96e9d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /update-product
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  UpdateProductCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/3b38556ae4653ec70f876f2417e96e9d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /update-product
            Method: OPTIONS
  DisabledProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/5967d1f3ededef49d55cb8a32695e43e
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /disabled-product
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  DisabledProductCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/5967d1f3ededef49d55cb8a32695e43e
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /disabled-product
            Method: OPTIONS
  ForgotPassFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/48680168a52cc22b390f7113e38802a6
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /forgot-password
            Method: POST
      Environment:
        Variables:
          HOST_MAIL: smtp.hostinger.mx
          USER_MAIL: contacto@mimarchante.mx
          PASS_MAIL: '!dSc3i!0mY9'
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
  ForgotPassCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/5967d1f3ededef49d55cb8a32695e43e
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /forgot-password
            Method: OPTIONS
  ChangePassFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/c506e1bb03a10cc1aeb7d7de1f5ece23
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /change-pass
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
  ChangePassCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/c506e1bb03a10cc1aeb7d7de1f5ece23
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /change-pass
            Method: OPTIONS
  GetCategoryProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/3b0105414a7372a28acc3c3795119e07
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-category-product/{type_category}
            Method: GET
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  GetCategoryProductCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/3b0105414a7372a28acc3c3795119e07
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-category-product/{type_category}
            Method: OPTIONS
  GetCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/2f805dcbbb5e6b32d4975349a206d839
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-postal-code/{type_market}
            Method: GET
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  GetCPCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/2f805dcbbb5e6b32d4975349a206d839
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-postal-code/{type_market}
            Method: OPTIONS
  GetMarketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/817dbbfe9b57c5af61af54f293a78db9
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-cat-markets/{id_cp}
            Method: GET
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  GetMarketsCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/817dbbfe9b57c5af61af54f293a78db9
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-cat-markets/{id_cp}
            Method: OPTIONS
  GetAssociatedTenantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/0faeb69072269435f61e19d6d8074c3d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-associated-tenants
            Method: POST
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  GetAssociatedTenantsCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/0faeb69072269435f61e19d6d8074c3d
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-associated-tenants
            Method: OPTIONS
  GetMarketsRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/8361f22a3d84ed8eb45e2f2e978bc178
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-markets-register/{type_market}
            Method: GET
      Environment:
        Variables:
          USER_DB: admin
          PASSWORD_DB: mARchant3
          HOST_DB: mimarchanteinstance.c9qv7s01ybr2.us-east-2.rds.amazonaws.com
          PORT_DB: '3306'
          NAME_DB: marchante
          KEY_JWT: 777tThZ-68V57rmQaPTs4tyx-yjlWfHbb_xEXU72giMEKNP0oJcoJKrs5GLfIlw_dRfz23fV45Nb8LJbovlGvepmw0ShXMMBKnNi9BAu7U8JHsa7lTMMbGB6vOuiEjCQn8vxQx-lVowxtoGFFwuOUwv7BVwaz3u_S6vERHEOJT_K4-N-kHFHAAWSdHnq3xUwjsRBh6SV9RnrL5RSNaVda25Gb%h_]1lHfOp_YTUEBffwEbH47[5=KAV-vXKEm1_onyqAQEcyVI6y4r--l2sXh19sllSPy3FMoGAmXAxAjg6vIE666njAVKTn1C_iCVG7ZdBaolWohEr_TLBpem7q-QvZfyqNrlshvc_gqOdX54WrY
  GetMarketsRegisterCors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://bucketmarchante/8361f22a3d84ed8eb45e2f2e978bc178
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get-markets-register/{type_market}
            Method: OPTIONS
Outputs:
  RegisterUserAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register/
  LoginAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/
  AddProductsAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add-products/
  GetProductsAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-products/
  UpdateProductsAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-product/
  DisabledProductsAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/disabled-product/
  ForgotPassAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/forgot-password/
  ChangePassAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/change-pass/
  GetCategoryProductAPI:
    Description: Obtener categorias de productos
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-category-product/
  GetCPAPI:
    Description: Obtener codigos postales de mercados o tianguis
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-postal-code/
  GetMarketsAPI:
    Description: Obtener tianguis o mercados
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-cat-markets/
  GetAssociatedTenantsAPI:
    Description: Obtener locatarios asociados a un tipo de producto
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-associated-tenants/
  GetMarketsRegisterAPI:
    Description: "Obtener mercados \xF3 tianguis en la secci\xF3n de registro"
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-markets-register/
